### ISSUE TITLE
restart interface after connection

### ISSUE THREAD

**Issue by khainguyenvan** [Indigo744/wlanprofilemanager-ps#1]
First, thanks for your amazing and easy-to-use application. But in my opinion, I think you should remove the restart interface function if full config is provided. Do I miss something important? Correct me if I am wrong. Many thanks.

**Comment by Indigo744** [comment]
Hello,

Thank you for your kind words. It is always appreciated 😄 

However, I fail to understand your issue.

An interface _may_ need to be restarted in order to force the new configuration to take effect IF:
- DHCP needs to be activated on interface
- Static IP needs to be activated on interface

If you know a way to force Windows to take into account these settings without resorting to restart the interface, please tell me and I'll be glad to update the script!

Thank you!

**Comment by khainguyenvan** [comment]
In my case, I set custom IP/DNS if I connect to a specific network and the adapter will fallback to default settings if I try connect to unknown one. I feel some disruption when I change the network, so I comment all need_restart and it works fine. Just curious why you restart the interface. Thanks for your information. That useful to me.

**Comment by Indigo744** [comment]
This is surprising. On my computer, the new settings wont take effect until I restart the interface. Maybe it's related to the driver or something.

If you want, I could add an option in the interface definition to avoid interface restart. Would that be good for you?

**Comment by Indigo744** [comment]
I've added the option `_opt_restart_itf` ([version 1.3](https://github.com/Indigo744/wlanprofilemanager-ps/releases/tag/1.3)). 

In your case, you should set it to `Never`.
